language_prefix: true # 启用时，自动添加字典key的语种前缀、对多词典隔离
# word /tab phoneme_1 /空格 phoneme_2 ...
dictionaries:
  zh: dictionaries/opencpop-extension.txt
  ja: dictionaries/japanese_dict_full.txt
#  en: dictionaries/ds_cmudict-07b.txt
#  yue: dictionaries/jyutping_dict.txt

datasets_config: # 数据集
  - configs/datasets_config.yaml

binary_folder: data/binary_units # 预处理结果文件夹

multiprocess_works: 0 # 预处理线程数和暂存队列大小，数据量过少（5h以内）不建议开启。每6-8g内存、6g显存可开1个worker。
multiprocess_max_size: 200  # size * num_works，过大需保证内存足够
multiprocess_start_size: 100  # 最小启动数据量

units_cache: true # tools/pretreatment_hubert.py 使用hubert预处理units，保存为wav同名npy文件。避免对照实验时反复预处理。
valid_set_size: 20 # valid_set_size大于0时，按数量随机抽取、否则使用datasets内的验证集
max_length: 45 # 单条音频最大时长

# 暂未启用
extra_phonemes: [ ]

# 与语种无关，需要无标注下自动识别
non_speech_phonemes:
  - AP
  - EP

# 无声音素
silent_phonemes:
  - SP
  - <SP>
  - ''
  - pau
  - cl
  - CL
  - AP
  - EP
  - GS

# 参照readme表格配置
hubert_config:
  encoder: cnhubert
  model_path: dependencies/chinese-hubert-base
  sample_rate: 16000
  hop_size: 320
  channel: 768

# 仅tb绘图使用
melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 16000
  clamp: 0.00001

# 不建议开启
merged_phoneme: False
# merge phonemes
merged_phoneme_groups:
  - - zh/f
    - en/f
  - - zh/m
    - en/m
    - ja/m
  - - zh/w
    - en/w
    - ja/w
  - - zh/s
    - en/s
    - ja/s
  - - zh/n
    - en/n
    - ja/n
  - - zh/c
    - ja/ts
  - - zh/y
    - en/y
    - ja/y
  - - zh/l
    - en/l
  - - zh/x
    - ja/sh
  - - ja/z
    - en/z

