datasets_config: configs/datasets_config.yaml

binary_folder: data/binary_base_mel

# 预处理线程数和暂存队列大小，数据量过少（5h以内）、内存低于16g、显存低于8g不建议开启。
multiprocess_works: 0
# size * num_works，过大需保证内存足够
multiprocess_max_size: 200
# 最小启动数据量
multiprocess_start_size: 100

# valid_set_size大于0时，按数量随机抽取、否则使用datasets内的验证集
valid_set_size: 0
max_length: 45 # 单条音频最大时长

# 参照readme表格配置, mel使用melspec_config和hubert_config的channel(与n_mels一致)
hubert_config:
  encoder: mel
  model_path: dependencies/cnhubert # encoder为mel时仅channel有效
  sample_rate: 16000
  hop_size: 320
  channel: 128

melspec_config:
  n_mels: 128
  sample_rate: 44100
  win_length: 1024
  hop_length: 512
  n_fft: 2048
  fmin: 40
  fmax: 16000
  clamp: 0.00001
