model_name: hfa-model-mel

# settings
float32_matmul_precision: high
random_seed: 123456

binary_folder: data/binary_base_mel

# 开的太高需要有足够内存、cpu
dataloader_workers: 2
dataloader_prefetch_factor: 2
oversampling_weights: [ 1, 1, 1, 1 ] # full_label, weak_label, no_label, evaluate，此项无效、勿修改
batch_max_length: 100 # unit: seconds，大数据量（10h以上）精标可以考虑200、400，自行比较效果
binning_length: 1000 # unit: seconds
drop_last: False

num_valid_plots: 20 # val、evaluate各项最大绘制数量
# 绘制evaluate/计算loss，暂未评估加入loss的效果，开启后val极慢
draw_evaluate: False
get_evaluate_loss: False

# model，建议不修改，或对照实验
model:
  hidden_dims: 192
  down_sampling_factor: 2
  down_sampling_times: 3
  channels_scaleup_factor: 1.3

optimizer_config:
  gamma: 0.9999
  total_steps: 100000
  weight_decay: 0.1
  lr:
    backbone: 0.001
    head: 0.001
  freeze:
    backbone: False
    head: False

loss_config:
  losses:
    weights: [ 8.0, 0.1, 0.01, 0.1, 2.0 ]
    enable_RampUpScheduler: [ False,False,False,False,True ]
  function:
    num_bins: 10
    alpha: 0.999
    label_smoothing: 0.08
    pseudo_label_ratio: 0.3

# trainer
accelerator: auto
devices: auto # num_devices
precision: bf16-mixed # bf16-mixed , 32-true
gradient_clip_val: 0.5
gradient_clip_algorithm: norm #value
val_check_interval: 1000 # 0.25

save_top_k: 5
save_every_steps: 1000
